// Generated by PDNA.
const pdna = @import("pdna_song_adapter.zig");

const song1_lead_notes = [_]pdna.NoteEvent{
    // Order 1: song_1_pattern_1
    .{ .step = 3, .length = 1, .note = 77, .velocity = 0.7 },
    .{ .step = 4, .length = 1, .note = 76, .velocity = 0.7 },
    .{ .step = 5, .length = 1, .note = 77, .velocity = 0.7 },
    .{ .step = 6, .length = 2, .note = 74, .velocity = 0.7 },
    .{ .step = 9, .length = 1, .note = 77, .velocity = 0.7 },
    .{ .step = 10, .length = 1, .note = 72, .velocity = 0.7 },
    .{ .step = 11, .length = 1, .note = 77, .velocity = 0.7 },
    .{ .step = 12, .length = 14, .note = 71, .velocity = 0.7 },
    // Order 2: song1_pattern_2
    .{ .step = 35, .length = 1, .note = 76, .velocity = 0.7 },
    .{ .step = 36, .length = 1, .note = 74, .velocity = 0.7 },
    .{ .step = 37, .length = 1, .note = 76, .velocity = 0.7 },
    .{ .step = 38, .length = 2, .note = 72, .velocity = 0.7 },
    .{ .step = 41, .length = 1, .note = 76, .velocity = 0.7 },
    .{ .step = 42, .length = 1, .note = 71, .velocity = 0.7 },
    .{ .step = 43, .length = 1, .note = 76, .velocity = 0.7 },
    .{ .step = 44, .length = 14, .note = 69, .velocity = 0.7 },
};

const song1_harmony_notes = [_]pdna.NoteEvent{
    // Order 1: song_1_pattern_1
    .{ .step = 2, .length = 1, .note = 62, .velocity = 0.7 },
    .{ .step = 6, .length = 1, .note = 62, .velocity = 0.7 },
    .{ .step = 9, .length = 1, .note = 62, .velocity = 0.7 },
    .{ .step = 12, .length = 1, .note = 62, .velocity = 0.7 },
    .{ .step = 15, .length = 1, .note = 62, .velocity = 0.7 },
    .{ .step = 18, .length = 1, .note = 67, .velocity = 0.7 },
    .{ .step = 22, .length = 1, .note = 67, .velocity = 0.7 },
    .{ .step = 25, .length = 1, .note = 67, .velocity = 0.7 },
    .{ .step = 28, .length = 1, .note = 67, .velocity = 0.7 },
    .{ .step = 31, .length = 1, .note = 67, .velocity = 0.7 },
    // Order 2: song1_pattern_2
    .{ .step = 34, .length = 1, .note = 69, .velocity = 0.7 },
    .{ .step = 38, .length = 1, .note = 69, .velocity = 0.7 },
    .{ .step = 41, .length = 1, .note = 69, .velocity = 0.7 },
    .{ .step = 44, .length = 1, .note = 69, .velocity = 0.7 },
    .{ .step = 47, .length = 1, .note = 69, .velocity = 0.7 },
    .{ .step = 50, .length = 1, .note = 65, .velocity = 0.7 },
    .{ .step = 54, .length = 1, .note = 65, .velocity = 0.7 },
    .{ .step = 57, .length = 1, .note = 65, .velocity = 0.7 },
    .{ .step = 60, .length = 1, .note = 64, .velocity = 0.7 },
    .{ .step = 63, .length = 1, .note = 64, .velocity = 0.7 },
};

const song1_bass_notes = [_]pdna.NoteEvent{
    // Order 1: song_1_pattern_1
    .{ .step = 2, .length = 14, .note = 38, .velocity = 0.7 },
    .{ .step = 18, .length = 8, .note = 43, .velocity = 0.7 },
    // Order 2: song1_pattern_2
    .{ .step = 34, .length = 14, .note = 45, .velocity = 0.7 },
    .{ .step = 50, .length = 8, .note = 41, .velocity = 0.7 },
    .{ .step = 58, .length = 4, .note = 40, .velocity = 0.7 },
};

const song1_percussion_notes = [_]pdna.NoteEvent{
    // Order 1: song_1_pattern_1
    .{ .step = 0, .length = 1, .note = 30, .velocity = 0.7 },
    .{ .step = 4, .length = 1, .note = 36, .velocity = 0.7 },
    .{ .step = 8, .length = 1, .note = 30, .velocity = 0.7 },
    .{ .step = 12, .length = 1, .note = 36, .velocity = 0.7 },
    .{ .step = 16, .length = 1, .note = 30, .velocity = 0.7 },
    .{ .step = 20, .length = 1, .note = 36, .velocity = 0.7 },
    .{ .step = 24, .length = 1, .note = 30, .velocity = 0.7 },
    .{ .step = 28, .length = 1, .note = 36, .velocity = 0.7 },
    // Order 2: song1_pattern_2
    .{ .step = 32, .length = 1, .note = 30, .velocity = 0.7 },
    .{ .step = 36, .length = 1, .note = 36, .velocity = 0.7 },
    .{ .step = 40, .length = 1, .note = 30, .velocity = 0.7 },
    .{ .step = 44, .length = 1, .note = 36, .velocity = 0.7 },
    .{ .step = 48, .length = 1, .note = 30, .velocity = 0.7 },
    .{ .step = 52, .length = 1, .note = 36, .velocity = 0.7 },
    .{ .step = 56, .length = 1, .note = 30, .velocity = 0.7 },
    .{ .step = 60, .length = 1, .note = 36, .velocity = 0.7 },
};

pub const song1 = pdna.SongPreset{
    .steps_per_second = 6.666666666666667,
    .length_steps = 64,
    .loop_start_step = 0,
    .loop_end_step_inclusive = 63,
    .tracks = .{
        .{
            .volume = 1.0,
            .voices = &[_]pdna.InstrumentVoicePreset{
                .{
                    .key_range = .{ .first = 0, .last = 127 },
                    .voice = .{ .waveform = .square, .envelope = .{ .attack_s = 0.005, .decay_s = 0.04, .sustain = 0.55, .release_s = 0.03, .curvature = 0.0, .velocity_sensitivity = 1.0, .legato = false, .retrigger = true, .rate_scaling = null }, .volume = 0.12, .pitch_source = .{ .vibrato = .{ .shape = .sine, .rate_hz = 3.0, .center = 0.0, .depth = 0.2, .holdoff_s = 0.0, .ramp_s = 0.08, .start_phase = 0.0, .retrigger = true } }, .amplitude_lfo = null },
                },
            },
            .notes = &song1_lead_notes,
            .pitch_automation = &.{},
        },
        .{
            .volume = 1.0,
            .voices = &[_]pdna.InstrumentVoicePreset{
                .{
                    .key_range = .{ .first = 0, .last = 127 },
                    .voice = .{ .waveform = .triangle, .envelope = .{ .attack_s = 0.005, .decay_s = 0.04, .sustain = 0.55, .release_s = 0.03, .curvature = 0.0, .velocity_sensitivity = 1.0, .legato = false, .retrigger = true, .rate_scaling = null }, .volume = 1.0, .pitch_source = .none, .amplitude_lfo = null },
                },
            },
            .notes = &song1_harmony_notes,
            .pitch_automation = &.{},
        },
        .{
            .volume = 1.0,
            .voices = &[_]pdna.InstrumentVoicePreset{
                .{
                    .key_range = .{ .first = 0, .last = 127 },
                    .voice = .{ .waveform = .sawtooth, .envelope = .{ .attack_s = 0.005, .decay_s = 0.04, .sustain = 0.55, .release_s = 0.5, .curvature = 0.0, .velocity_sensitivity = 1.0, .legato = false, .retrigger = true, .rate_scaling = null }, .volume = 0.5, .pitch_source = .none, .amplitude_lfo = null },
                },
            },
            .notes = &song1_bass_notes,
            .pitch_automation = &[_]pdna.PitchPoint{
                .{ .step = 3, .semitones = 0.0, .interpolate = false },
                .{ .step = 5, .semitones = 7.0, .interpolate = true },
            },
        },
        .{
            .volume = 1.0,
            .voices = &[_]pdna.InstrumentVoicePreset{
                .{
                    .key_range = .{ .first = 36, .last = 36 },
                    .voice = .{ .waveform = .noise, .envelope = .{ .attack_s = 0.001, .decay_s = 0.08, .sustain = 0.0, .release_s = 0.04, .curvature = 0.0, .velocity_sensitivity = 1.0, .legato = false, .retrigger = true, .rate_scaling = null }, .volume = 0.8, .pitch_source = .none, .amplitude_lfo = null },
                },
                .{
                    .key_range = .{ .first = 35, .last = 35 },
                    .voice = .{ .waveform = .square, .envelope = .{ .attack_s = 0.001, .decay_s = 0.04, .sustain = 0.0, .release_s = 0.003, .curvature = 0.0, .velocity_sensitivity = 1.0, .legato = false, .retrigger = true, .rate_scaling = null }, .volume = 0.8, .pitch_source = .none, .amplitude_lfo = null },
                },
                .{
                    .key_range = .{ .first = 37, .last = 126 },
                    .voice = .{ .waveform = .square, .envelope = .{ .attack_s = 0.005, .decay_s = 0.04, .sustain = 0.55, .release_s = 0.03, .curvature = 0.0, .velocity_sensitivity = 1.0, .legato = false, .retrigger = true, .rate_scaling = null }, .volume = 0.12, .pitch_source = .none, .amplitude_lfo = null },
                },
                .{
                    .key_range = .{ .first = 0, .last = 34 },
                    .voice = .{ .waveform = .square, .envelope = .{ .attack_s = 0.005, .decay_s = 0.04, .sustain = 0.55, .release_s = 0.03, .curvature = 0.0, .velocity_sensitivity = 1.0, .legato = false, .retrigger = true, .rate_scaling = null }, .volume = 0.12, .pitch_source = .none, .amplitude_lfo = null },
                },
                .{
                    .key_range = .{ .first = 127, .last = 127 },
                    .voice = .{ .waveform = .square, .envelope = .{ .attack_s = 0.005, .decay_s = 0.04, .sustain = 0.55, .release_s = 0.03, .curvature = 0.0, .velocity_sensitivity = 1.0, .legato = false, .retrigger = true, .rate_scaling = null }, .volume = 0.12, .pitch_source = .none, .amplitude_lfo = null },
                },
            },
            .notes = &song1_percussion_notes,
            .pitch_automation = &.{},
        },
    },
};
